const USER_ROLES = [
  "COMPANY_ADMIN",
  "FLEET_MANAGER",
  "DRIVER",
  "SAFETY_OFFICER",
  "EXPENSE_MANAGER",
  "FINANCIAL_ANALYST",
];

const VEHICLE_STATUSES = ["AVAILABLE", "ON_TRIP", "IN_SHOP", "RETIRED"];
const DRIVER_STATUSES = ["AVAILABLE", "ON_TRIP", "OFF_DUTY", "SUSPENDED"];
const TRIP_STATUSES = ["DRAFT", "DISPATCHED", "COMPLETED", "CANCELLED"];

module.exports = { USER_ROLES, VEHICLE_STATUSES, DRIVER_STATUSES, TRIP_STATUSES };
