const USER_ROLES = [
  "COMPANY_ADMIN",
  "FLEET_MANAGER",
  "DRIVER",
  "SAFETY_OFFICER",
  "EXPENSE_MANAGER",
  "FINANCIAL_ANALYST",
];

const FLEET_MANAGEMENT_ROLES = ["COMPANY_ADMIN", "FLEET_MANAGER"];
const EXPENSE_MANAGEMENT_ROLES = [...FLEET_MANAGEMENT_ROLES, "EXPENSE_MANAGER"];
const TRIP_VIEW_ROLES = [...FLEET_MANAGEMENT_ROLES, "SAFETY_OFFICER", "FINANCIAL_ANALYST"];
const FINANCIAL_VIEW_ROLES = [...FLEET_MANAGEMENT_ROLES, "FINANCIAL_ANALYST"];

const VEHICLE_STATUSES = ["AVAILABLE", "ON_TRIP", "IN_SHOP", "RETIRED"];
const DRIVER_STATUSES = ["AVAILABLE", "ON_TRIP", "OFF_DUTY", "SUSPENDED"];
const TRIP_STATUSES = ["DRAFT", "DISPATCHED", "COMPLETED", "CANCELLED"];

module.exports = {
  USER_ROLES,
  FLEET_MANAGEMENT_ROLES,
  EXPENSE_MANAGEMENT_ROLES,
  TRIP_VIEW_ROLES,
  FINANCIAL_VIEW_ROLES,
  VEHICLE_STATUSES,
  DRIVER_STATUSES,
  TRIP_STATUSES,
};
